lcqd_api_user:
    type: rest
    prefix: /v1
    resource: LCQD\ApiBundle\Controller\UserController
    name_prefix:  api_1_

lcqd_api_avatars:
    type: rest
    prefix: /v1
    resource: LCQD\ApiBundle\Controller\AvatarsController
    name_prefix:  api_1_

lcqd_api_avatar:
    type: rest
    prefix: /v1
    resource: LCQD\ApiBundle\Controller\AvatarController
    name_prefix:  api_1_