parameters:
#    lcqd_api.example.class: LCQD\ApiBundle\Example

services:
#    lcqd_api.example:
#        class: %lcqd_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
