parameters:
#    lcqd_user.example.class: LCQD\UserBundle\Example

services:
#    lcqd_user.example:
#        class: %lcqd_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
