fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        LCQD\AppBundle\Entity\Client
    access_token_class:  LCQD\AppBundle\Entity\AccessToken
    refresh_token_class: LCQD\AppBundle\Entity\RefreshToken
    auth_code_class:     LCQD\AppBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username
