lcqd_app:
    resource: "@LCQDAppBundle/Resources/config/routing.yml"
    prefix:   /

lcqd_app_api:
    type: rest
    resource: "@LCQDAppBundle/Resources/config/routing_api.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

