lcqd_app:
    resource: "@LCQDAppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

lcqd_api:
    type: rest
    resource: "@LCQDApiBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

