security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        api:
            pattern: ^/api
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /api/login
                check_path: /api/login_check
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/api/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin/, role: ROLE_ADMIN }
        - { path: ^/api/*, role: ROLE_USER }
        