# Api routing
lcqd_app_api_user:
    type: rest
    prefix: /v1
    resource: LCQD\AppBundle\Controller\Api\UserController
    name_prefix:  api_1_

lcqd_app_api_avatars:
    type: rest
    prefix: /v1
    resource: LCQD\AppBundle\Controller\Api\AvatarsController
    name_prefix:  api_1_

lcqd_app_api_avatar:
    type: rest
    prefix: /v1
    resource: LCQD\AppBundle\Controller\Api\AvatarController
    name_prefix:  api_1_
